### ISSUE TITLE
Error in debug mode

### ISSUE THREAD

**Issue by tmnchan** [juanfranblanco/vscode-solidity#136]
Hello,
I was trying to run in debug mode. I just made npm install and then pushed F5. I opened the .sol file and got this error in debug console. Did you face it before?
I was trying to debug it on different versions of VSCode: 1.28, 1.29, 1.33.
OS: Windows 10,
Node: 10.15.3
Npm: 6.4.1

```
Activating extension 'JuanBlanco.solidity' failed: A dynamic link library (DLL) initialization routine failed.

\\?\D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\scrypt\build\Release\scrypt.node.
Activating extension `JuanBlanco.solidity` failed:  A dynamic link library (DLL) initialization routine failed.

\\?\D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\scrypt\build\Release\scrypt.node
Here is the error stack:  Error: A dynamic link library (DLL) initialization routine failed.

\\?\D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\scrypt\build\Release\scrypt.node
	at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
	at Object.Module._extensions..node (module.js:671:18)
	at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\scrypt\index.js:3:20)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\scrypt\index.js:388:3)
	at Module.t._initNodeRequire.o._compile (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\scrypt.js\node.js:1:169)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\scrypt.js\node.js:9:3)
	at Module.t._initNodeRequire.o._compile (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\web3-eth-accounts\src\index.js:35:16)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\web3-eth-accounts\src\index.js:536:3)
	at Module.t._initNodeRequire.o._compile (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\web3-eth\src\index.js:37:16)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\web3-eth\src\index.js:468:3)
	at Module.t._initNodeRequire.o._compile (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\web3\src\index.js:33:11)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\web3\src\index.js:81:3)
	at Module.t._initNodeRequire.o._compile (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\truffle-provider\index.js:2:12)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\truffle-provider\index.js:46:3)
	at Module.t._initNodeRequire.o._compile (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\truffle-config\index.js:3:18)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\node_modules\truffle-config\index.js:395:3)
	at Module.t._initNodeRequire.o._compile (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:896)
	at Function.t.getExtensionPathIndex.then.o._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:885)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:643:436)
	at Module.require (module.js:586:17)
	at n (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:808)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\out\src\analysis\mythx\index.js:23:16)
	at Object.<anonymous> (D:\Projects\VsCodeExtensions\vscode-solidity-master\out\src\analysis\mythx\index.js:364:3)
	at Module.t._initNodeRequire.o._compile (c:\Users\thanmin.chan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:72)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
```

**Comment by juanfranblanco** [comment]
This is due to having added script as as a dependency, this won't work as it gets compiled specific per Operating System. What branch are you using?

**Comment by tmnchan** [comment]
@juanfranblanco I'm using a master branch

**Comment by tmnchan** [comment]
I didn't change code at all. Just cloned a repo and then tried to debug it

**Comment by juanfranblanco** [comment]
Are you in master latest? You should not have a dependency on scrypt

**Comment by juanfranblanco** [comment]
I can see also a dependency on Web3 Eth

**Comment by tmnchan** [comment]
That's right. And web3-eth is a dependency of web3

**Comment by juanfranblanco** [comment]
Yes the Web3 Eth accounts is the one that brings the dependency of scrypt.

**Comment by juanfranblanco** [comment]
Yes that is one of the main issues of Web3 and crypto. Also it cannot browserified as it is a node module. I did force it for testrpc a long time ago for portability, but is not out of the box.

**Comment by tmnchan** [comment]
I see, thanks for your quick response.
Look's like i didn't get the latest master. So i still have dependencies on truffle-* libs (truffle-artifactor, truffle-config and so on). 
But it's still interesting how it worked before. I see in this commit https://github.com/juanfranblanco/vscode-solidity/commit/90795364f517dbb36d0b24a115ce1aff24a663c8 that there was a specific requirements of installation for the previous version. Is says "Starting with Microsoft code 1.31 (or 1.32) you will get a crash when you try to run this code" - could it be related with the error above?

**Comment by juanfranblanco** [comment]
That did not work, hence it was pulled out. It may have work locally if compiled the dependencies.

**Comment by juanfranblanco** [comment]
That bug issue, was one of the generic problems. I removed that issue, but whilst "working" locallyafer c compilation, it does not work in different oses. So it needs further investigation.

**Comment by juanfranblanco** [comment]
I am closing this now
