### ISSUE TITLE
TypeError: soljson.cwrap is not a function

### ISSUE THREAD

**Issue by mudgen** [juanfranblanco/vscode-solidity#187]
My Solidity Language Server crashes every time with the error: "TypeError: soljson.cwrap is not a function"

This is my settings: 
```
"solidity.compileUsingRemoteVersion" : "0.6.12",
    "solidity.enabledSolhint": true,
    "solidity.validationDelay": 1500
    "solidity.solhintRules": {
    }
```

Here is the full error info:
```
TypeError: soljson.cwrap is not a function
TypeError: soljson.cwrap is not a function
c:\Users\mudge\.vscode\extensions\juanblanco.solidity-0.0.74\node_modules\solc\soljson.js:1
null;var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}var read_,readAsync,readBinary,setWindowTitle;var nodeFS;var nodePath;if(ENV

RuntimeError: abort(TypeError: soljson.cwrap is not a function). Build with -s ASSERTIONS=1 for more info.
    at process.abort (c:\Users\mudge\.vscode\extensions\juanblanco.solidity-0.0.74\node_modules\solc\soljson.js:1:12830)
    at process.emit (events.js:203:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
[Info  - 9:36:31 AM] Connection to server got closed. Server will restart.
TypeError: soljson.cwrap is not a function
TypeError: soljson.cwrap is not a function
c:\Users\mudge\.vscode\extensions\juanblanco.solidity-0.0.74\node_modules\solc\soljson.js:1
null;var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}var read_,readAsync,readBinary,setWindowTitle;var nodeFS;var nodePath;if(ENV

RuntimeError: abort(TypeError: soljson.cwrap is not a function). Build with -s ASSERTIONS=1 for more info.
    at process.abort (c:\Users\mudge\.vscode\extensions\juanblanco.solidity-0.0.74\node_modules\solc\soljson.js:1:12830)
    at process.emit (events.js:203:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
[Info  - 9:36:45 AM] Connection to server got closed. Server will restart.
```

**Comment by mudgen** [comment]
Help?

**Comment by juanfranblanco** [comment]
Hey, sorry I missed this. That is not the right format for the compiler. If you right click on the solidity file, you will be able to select the version in the correct format.

**Comment by juanfranblanco** [comment]
![image](https://user-images.githubusercontent.com/562371/89129546-10f8b700-d4f6-11ea-9265-5f0c2c54a3e4.png)
![image](https://user-images.githubusercontent.com/562371/89129576-4bfaea80-d4f6-11ea-981a-25ddbc01ba9c.png)

**Comment by mudgen** [comment]
@juanfranblanco Thank you that works!

**Comment by pitieu** [comment]
Just as a help how i fixed this `soljson.cwrap` issue.
I installed solc locally with the version i wanted and then had to reference version to local npm folder

```
module.exports = {
  compilers: {
    solc: {
      version: "./node_modules/solc/",
      settings: {
       optimizer: {
         enabled: true,
         runs: 200
       },
      }
    }
  }
};
```

This seemed to fix it for me. By referencing a version number it would always compile with wrong solc version.

**Comment by juanfranblanco** [comment]
@pitieu What were your settings?
