### ISSUE TITLE
The solidity language server crashed 5 times

### ISSUE THREAD

**Issue by Dmdv** [juanfranblanco/vscode-solidity#201]
VS Code version: latest

User setting:

```
"solidity.compileUsingRemoteVersion": "latest"
```

Workspace setting:

    "solidity.compileUsingRemoteVersion": "v0.7.5+commit.eb77ed08",
    "solidity.enableLocalNodeCompiler": false,

Console output:
```

SyntaxError: missing ) after argument list
SyntaxError: missing ) after argument list
c:\Users\dimad\.vscode\extensions\juanblanco.solidity-0.0.76\node_modules\solc\soljson.js:1
null;var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}var read_,readAsync,readBinary,setWindowTitle;var nodeFS;var nodePath;if(ENV

RuntimeError: abort(SyntaxError: missing ) after argument list). Build with -s ASSERTIONS=1 for more info.
    at process.abort (c:\Users\dimad\.vscode\extensions\juanblanco.solidity-0.0.76\node_modules\solc\soljson.js:1:13938)
    at process.emit (events.js:223:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:32)
[Info  - 6:52:40 PM] Connection to server got closed. Server will restart.
SyntaxError: missing ) after argument list
SyntaxError: missing ) after argument list
c:\Users\dimad\.vscode\extensions\juanblanco.solidity-0.0.76\node_modules\solc\soljson.js:1
null;var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}var read_,readAsync,readBinary,setWindowTitle;var nodeFS;var nodePath;if(ENV

RuntimeError: abort(SyntaxError: missing ) after argument list). Build with -s ASSERTIONS=1 for more info.
    at process.abort (c:\Users\dimad\.vscode\extensions\juanblanco.solidity-0.0.76\node_modules\solc\soljson.js:1:13938)
    at process.emit (events.js:223:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:32)
[Info  - 6:52:45 PM] Connection to server got closed. Server will restart.
SyntaxError: missing ) after argument list
SyntaxError: missing ) after argument list
c:\Users\dimad\.vscode\extensions\juanblanco.solidity-0.0.76\node_modules\solc\soljson.js:1
null;var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}var read_,readAsync,readBinary,setWindowTitle;var nodeFS;var nodePath;if(ENV

RuntimeError: abort(SyntaxError: missing ) after argument list). Build with -s ASSERTIONS=1 for more info.
    at process.abort (c:\Users\dimad\.vscode\extensions\juanblanco.solidity-0.0.76\node_modules\solc\soljson.js:1:13938)
    at process.emit (events.js:223:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:32)
[Info  - 6:52:48 PM] Connection to server got closed. Server will restart.
SyntaxError: missing ) after argument list
SyntaxError: missing ) after argument list
c:\Users\dimad\.vscode\extensions\juanblanco.solidity-0.0.76\node_modules\solc\soljson.js:1
null;var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}var read_,readAsync,readBinary,setWindowTitle;var nodeFS;var nodePath;if(ENV

RuntimeError: abort(SyntaxError: missing ) after argument list). Build with -s ASSERTIONS=1 for more info.
    at process.abort (c:\Users\dimad\.vscode\extensions\juanblanco.solidity-0.0.76\node_modules\solc\soljson.js:1:13938)
    at process.emit (events.js:223:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:32)
[Info  - 6:52:50 PM] Connection to server got closed. Server will restart.
SyntaxError: missing ) after argument list
SyntaxError: missing ) after argument list
c:\Users\dimad\.vscode\extensions\juanblanco.solidity-0.0.76\node_modules\solc\soljson.js:1
null;var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}var read_,readAsync,readBinary,setWindowTitle;var nodeFS;var nodePath;if(ENV

RuntimeError: abort(SyntaxError: missing ) after argument list). Build with -s ASSERTIONS=1 for more info.
    at process.abort (c:\Users\dimad\.vscode\extensions\juanblanco.solidity-0.0.76\node_modules\solc\soljson.js:1:13938)
    at process.emit (events.js:223:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:32)
[Error - 6:52:53 PM] Connection to server got closed. Server will not be restarted.

```

![image](https://user-images.githubusercontent.com/805238/101654202-489ddf80-3a51-11eb-8bbe-1299609e3be9.png)

**Comment by juanfranblanco** [comment]
Hmm.. i have no issues..

**Comment by Dmdv** [comment]
> Hmm.. i have no issues.. Edit: Have you tried restarting?

Yes, many times. I spent the half-day trying to fix it. May be something I'm missing in settings?

**Comment by Dmdv** [comment]
I removed this extension and the error has gone:
https://marketplace.visualstudio.com/items?itemName=hosho.solidity-debugger

But not sure if it was the RC

**Comment by juanfranblanco** [comment]
Ohh I guess they forked and conflicted. Do you use it? Is it good? I could reach out and see if they want merge.

**Comment by juanfranblanco** [comment]
Ohh is pretty old but c#. Actually I have never got around to do that functionality I'll reach out

**Comment by juanfranblanco** [comment]
Closing this now.. although thinking on that other extension
