### ISSUE TITLE
VSCode output window continuously opens

### ISSUE THREAD

**Issue by CodeForcer** [juanfranblanco/vscode-solidity#236]
I'm experiencing the same behaviour as #41 with the latest version of vscode-solidity, I don't think the error is fixed.

Unfortunately this makes the extension unusable, as the output terminal pops up every single time a character is typed

**Comment by KohliSuraj** [comment]
I am having the same issue. I am not sure what I am doing wrong :( but the extension is unusable for me as well.

I am using Solidity version v0.8.0. Below is my solidity configuration:

`truffle version`
> Truffle v5.1.51 (core: 5.1.51)
> Solidity - 0.8.0 (solc-js)
> Node v12.18.3
> Web3.js v1.2.9

`Vscode local settings`


> {
>   "solidity.compileUsingRemoteVersion": "v0.8.0",
>   "solidity.enableLocalNodeCompiler": false,
>   "solidity.packageDefaultDependenciesContractsDirectory": "contracts",
>   "solidity.packageDefaultDependenciesDirectory": "node_modules",
>   "solidity.validationDelay": 1500,
>   "solidity.linter": "solhint",
>   "solidity.solhintRules": {
>     "avoid-sha3": "warn"
>   }
> }

This is what the output screen shows:

```
Debugger listening on ws://127.0.0.1:6009/297a03b8-6e30-4c4b-8f78-2f0906f6d4d2
For help, see: https://nodejs.org/en/docs/inspector
[Error - 5:15:19 PM] (node:59808) V8: /Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/node_modules/solc/soljson.js:3 Invalid asm.js: Invalid member of stdlib
[Error - 5:15:19 PM] (node:59808) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''
    at Module.require (internal/modules/cjs/loader.js:1074:11)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/out/src/solcCompiler.js:65:40
    at new Promise (<anonymous>)
    at SolcCompiler.intialiseCompiler (/Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/out/src/solcCompiler.js:49:16)
    at startValidation (/Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/out/src/server.js:127:22)
    at /Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/out/src/server.js:190:5
    at handleNotification (/Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/node_modules/vscode-jsonrpc/lib/main.js:476:43)
    at processMessageQueue (/Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/node_modules/vscode-jsonrpc/lib/main.js:248:17)
    at Immediate._onImmediate (/Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/node_modules/vscode-jsonrpc/lib/main.js:235:13)
[Error - 5:15:19 PM] (node:59808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[Error - 5:15:19 PM] (node:59808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 5:15:19 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:15:19 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:15:19 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:15:19 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:15:19 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:15:19 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:15:19 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:15:19 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:15:19 PM] line 51:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
Starting inspector on 127.0.0.1:6009 failed: address already in use
(node:59847) V8: /Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/node_modules/solc/soljson.js:3 Invalid asm.js: Invalid member of stdlib
[Error - 5:15:21 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:15:21 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:15:21 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:15:21 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:15:21 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:15:21 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:15:21 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:15:21 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:15:21 PM] line 51:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
[Error - 5:18:03 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:03 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:03 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:03 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:03 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:03 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:03 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:03 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:03 PM] line 51:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
Starting inspector on 127.0.0.1:6009 failed: address already in use
(node:59872) V8: /Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/node_modules/solc/soljson.js:3 Invalid asm.js: Invalid member of stdlib
[Error - 5:18:05 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:05 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:05 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:05 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:05 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:05 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:05 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:05 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:05 PM] line 51:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
[Error - 5:18:13 PM] line 48:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:13 PM] line 48:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:13 PM] line 48:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:13 PM] line 48:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:13 PM] line 48:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:13 PM] line 49:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:13 PM] line 49:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:13 PM] line 49:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:13 PM] line 52:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
Starting inspector on 127.0.0.1:6009 failed: address already in use
(node:59879) V8: /Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/node_modules/solc/soljson.js:3 Invalid asm.js: Invalid member of stdlib
[Error - 5:18:16 PM] line 48:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 48:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 48:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:16 PM] line 48:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 48:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:16 PM] line 49:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 49:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:16 PM] line 49:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 52:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
[Error - 5:18:16 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:16 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:16 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:16 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 51:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
[Error - 5:18:16 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:16 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:16 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:16 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:16 PM] line 51:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
Starting inspector on 127.0.0.1:6009 failed: address already in use
(node:59886) V8: /Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/node_modules/solc/soljson.js:3 Invalid asm.js: Invalid member of stdlib
[Error - 5:18:18 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:18 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:18 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:18 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:18 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:18 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:18 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:18 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:18 PM] line 51:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
[Error - 5:18:39 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:39 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:39 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:39 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:39 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:39 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:39 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:39 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:39 PM] line 52:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
[Error - 5:18:39 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:39 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:39 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:39 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:39 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:39 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:39 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:39 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:39 PM] line 52:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
[Error - 5:18:40 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:40 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:40 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:40 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:40 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:40 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:40 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:40 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:40 PM] line 51:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
Starting inspector on 127.0.0.1:6009 failed: address already in use
[Error - 5:18:41 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:41 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:41 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:41 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:41 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:41 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:41 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:41 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:41 PM] line 51:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
(node:59909) V8: /Users/a660597/.vscode/extensions/idrabenia.solidity-solhint-1.1.4/node_modules/solc/soljson.js:3 Invalid asm.js: Invalid member of stdlib
[Error - 5:18:41 PM] line 47:15 mismatched input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:41 PM] line 47:23 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:41 PM] line 47:34 mismatched input ',' expecting {';', '='}
[Error - 5:18:41 PM] line 47:43 extraneous input 'memory' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:41 PM] line 47:56 mismatched input ')' expecting {';', '='}
[Error - 5:18:41 PM] line 48:14 extraneous input '(' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:41 PM] line 48:19 mismatched input ',' expecting {';', '='}
[Error - 5:18:41 PM] line 48:27 mismatched input ')' expecting {'from', 'constant', 'internal', 'private', 'public', Identifier}
[Error - 5:18:41 PM] line 51:4 extraneous input 'function' expecting {<EOF>, 'pragma', 'import', 'contract', 'interface', 'library'}
```

**Comment by juanfranblanco** [comment]
Closing this, assuming problem with settings.
