### ISSUE TITLE
Jumping definition error

### ISSUE THREAD

**Issue by Ethnical** [juanfranblanco/vscode-solidity#366]
hello there, 
Got this weird error when i used `ctrl` to jump to a definition..
If anyone has an idea!

```
[2022-09-22 15:40:27.226] [exthost] [error] [JuanBlanco.solidity] provider FAILED
[2022-09-22 15:40:27.226] [exthost] [error] Error: Request textDocument/definition failed with message: Expected "!", "!=", "%", "%=", "&", "&&", "&=", "(", "*", "*=", "+", "++", "+=", ",", "-", "--", "-=", ".", "/", "/*", "/=", ";", "<", "<<", "<<=", "<=", "=", "==", ">", ">=", ">>", ">>=", ">>>", "?", "[", "^", "^=", "_", "address", "assembly", "emit", "false", "mapping", "revert", "true", "using", "v", "var", "{", "|", "|=", "||", "~", comment, end of line, number, string, or whitespace but "c" found. Line: 88, Column: 89
	at handleResponse (/Users/ethnical/.vscode/extensions/juanblanco.solidity-0.0.140/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
	at processMessageQueue (/Users/ethnical/.vscode/extensions/juanblanco.solidity-0.0.140/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
	at Immediate.<anonymous> (/Users/ethnical/.vscode/extensions/juanblanco.solidity-0.0.140/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
	at process.processImmediate (node:internal/timers:466:21)

```

**Comment by rori4** [comment]
bumping this. I think its still an issue if you want to follow a function. @juanfranblanco

**Comment by just2102** [comment]
Same issue.
