### ISSUE TITLE
Unable to Run Tools for Solidity

### ISSUE THREAD

**Issue by mrpathfindr** [juanfranblanco/vscode-solidity#397]
VSCode Version: Version: 1.76.1

Contract Solidity Version: pragma solidity ^0.8.17;

Global Solidity Compiler version: 0.8.17;

Solc select use version 0.8.17

VSCODE Output;

```

[Info  - 11:45:00] Connection to server got closed. Server will restart.
[Error - 11:45:09] Traceback (most recent call last):
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/lsp/server.py", line 264, in _task_done_callback
    task.result()
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/lsp/lsp_compiler.py", line 181, in run
    await self.__compilation_loop()
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/lsp/lsp_compiler.py", line 879, in __compilation_loop
    await self.__compile(self.__discovered_files)
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/lsp/lsp_compiler.py", line 816, in __compile
    await self.__run_detectors()
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/lsp/lsp_compiler.py", line 829, in __run_detectors
    for detection in detect(self.__config, self.__source_units):
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/analysis/detectors/api.py", line 486, in detect
    visit_map[ir_node.__class__](detector_instance, ir_node)
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/analysis/detectors/api.py", line 97, in <lambda>
    FunctionDefinition: lambda self, node: self.visit_function_definition(node),
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/analysis/detectors/missing_return.py", line 107, in visit_function_definition
    for det in check_missing_return(node):
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/analysis/detectors/missing_return.py", line 69, in check_missing_return
    solved, params = check_all_return_params_set(
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/analysis/detectors/utils.py", line 229, in check_all_return_params_set
    all_set = _check_all_return_params_set(
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/analysis/detectors/utils.py", line 263, in _check_all_return_params_set
    for vars in stmt.expression.assigned_variables:
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/ast/ir/expression/assignment.py", line 114, in assigned_variables
    return (resolve_node(node),)
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/ast/ir/expression/assignment.py", line 102, in resolve_node
    for path in resolve_node(node.expression)
  File "/usr/local/Caskroom/miniforge/base/lib/python3.8/site-packages/woke/ast/ir/expression/assignment.py", line 105, in resolve_node
    assert False, f"Unexpected node type: {type(node)}\n{self.source}"
AssertionError: Unexpected node type: <class 'woke.ast.ir.expression.function_call.FunctionCall'>
_unsafeAccess(ckpts, pos - 1).votes = SafeCast.toUint224(newWeight)

[Error - 11:45:09] The Tools for Solidity server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by juanfranblanco** [comment]
@mrpathfindr can you check the latest?
