### ISSUE TITLE
Intermittent Language Server Failures Leading to Inability to Use Go to Definition Feature

### ISSUE THREAD

**Issue by F01ivor4** [juanfranblanco/vscode-solidity#437]
### Description
When working with the vscode-solidity extension on WSL and Visual Studio Code, I am experiencing intermittent failures with the Solidity Language Server. These failures result in an inability to use the 'Go to Definition' feature among other functionality.

### Steps to Reproduce
1. Use the Solidity extension in a typical coding session within WSL.
2. After some time, the extension appears to break down randomly.

### Expected Behavior
The extension should consistently provide language server features such as definition lookup without interruption.

### Actual Behavior
The language server fails intermittently, as evidenced by the error logs, and the 'Go to Definition' feature ceases to work.

### Error Logs
Here is the output from the log when the issue occurs:
```
log.ts:441   ERR Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'sort'): Error: Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'sort')
    at handleResponse (/home/XXX/.vscode-server/extensions/juanblanco.solidity-0.0.163/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)
    at handleMessage (/home/XXX/.vscode-server/extensions/juanblanco.solidity-0.0.163/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)
    at processMessageQueue (/home/XXX/.vscode-server/extensions/juanblanco.solidity-0.0.163/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
    at Immediate.<anonymous> (/home/XXX/.vscode-server/extensions/juanblanco.solidity-0.0.163/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
    at processImmediate (node:internal/timers:476:21)
```
### Environment
- **VSCode Version**: v1.85, v1.84, 1.83
- **Solidity Extension Version**: 0.0.165
- **Operating System**: Windows Subsystem for Linux (WSL)

### Additional Context
- This problem persists even after ensuring that both Visual Studio Code and the Solidity extension are updated to the latest versions.

I appreciate your attention to this matter and look forward to a resolution. Thank you for your support.

**Comment by juanfranblanco** [comment]
@F01ivor4 it should be fixed now, can you let me know if you have any issues?

**Comment by F01ivor4** [comment]
I think it has already been fixed now, thanks!

**Comment by F01ivor4** [comment]
already fixed.
